### ISSUE TITLE
Getting access denied from Mammorion APIs (they block certain User-Agent header values)

### ISSUE THREAD

**Issue by coder89** [mikey0000/PyMammotion#69]
Hi,
I am trying to set up my Luba 1 mower with HASS and was getting "Access denied" error message in HASS.
I did some manual debugging of this problem and so far I concluded that it is related to this call:
https://github.com/mikey0000/PyMammotion/blob/209e220c350cdfaedbc70e1e50b1d08c8495c61e/pymammotion/http/http.py#L67

which is invoked here in the HASS integration:
https://github.com/mikey0000/Mammotion-HA/blob/614368ef382a6ab30c82a617a6e44e9a2c22f637/custom_components/mammotion/config_flow.py#L183

Strangely enough I ran exact same request from postman and I get the token as one would expect.
Not sure what could be causing this issue and I don't know how to debug this any further.

I tried curling from my HASS host device to see if I can reach that endpoint and I get 200 with the token data as well.
So the problem is purely when request is being made from HASS aiohttp session.
I could try to reflect the exact request that is being sent by aiohttp but I'm not that fluent in Python. I wrote a small script that uses aiohttp session inside hass integration to send that request and I get the same access denied error so at least I can reproduct this problem in isolation:
```
from aiohttp import ClientSession

                session = ClientSession("https://id.mammotion.com")
                async with session.post(
                    "/oauth/token",
                    data=dict(
                        username=account,
                        password=password,
                        client_id="MADKALUBAS",
                        client_secret="GshzGRZJjuMUgd2sYHM7",
                        grant_type="password",
                    ),
                ) as resp:
                    LOGGER.warn(f"resp {resp}")
                    LOGGER.warn(f"status {resp.ok}")
                    tmp = await resp.json()
                    LOGGER.warn(f"resp body {tmp}")
```

```
2024-12-16 13:42:28.880 WARNING (MainThread) [custom_components.mammotion] resp <ClientResponse(https://id.mammotion.com/oauth/token) [200 None]>
<CIMultiDictProxy('Date': 'Mon, 16 Dec 2024 12:42:28 GMT', 'Content-Type': 'application/json', 'Content-Length': '62', 'Connection': 'keep-alive', 'Request-Id': '173435294882546542637', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': '*', 'Access-Control-Allow-Methods': '*', 'Access-Control-Max-Age': '3600', 'Access-Control-Allow-Credentials': 'true', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Access-Control-Allow-Methods': '*')>

2024-12-16 13:42:28.880 WARNING (MainThread) [custom_components.mammotion] status True
2024-12-16 13:42:28.881 WARNING (MainThread) [custom_components.mammotion] resp body {'code': 403, 'msg': 'Access denied', 'msgTitle': None, 'data': None}
```

To add to this description my HASS instance is not publicly accessible (only on the local network) as I don't have a public IP setup for that instance (my current ISP doesn't want to allow it 😢).

I would appreciate if you could help me investigate this further.

**Comment by coder89** [comment]
same when I make this using requests in python
```
import requests

url = "https://id.mammotion.com/oauth/token"

payload = "client_id=MADKALUBAS&client_secret=GshzGRZJjuMUgd2sYHM7&username=test&password=test&grant_type=password"
headers = {
  'Content-Type': 'application/x-www-form-urlencoded',
  'Connection': 'keep-alive',
  'Request-Id': '173435294882546542637',
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': '*',
  'Access-Control-Allow-Methods': '*',
  'Access-Control-Max-Age': '3600',
  'Access-Control-Allow-Credentials': 'true',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
  'Access-Control-Allow-Methods': '*'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)
```

but from the same host this curl call works fine:
```
curl --location 'https://id.mammotion.com/oauth/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Connection: keep-alive' \
--header 'Request-Id: 173435294882546542637' \
--header 'Access-Control-Allow-Origin: *' \
--header 'Access-Control-Allow-Headers: *' \
--header 'Access-Control-Allow-Methods: *' \
--header 'Access-Control-Max-Age: 3600' \
--header 'Access-Control-Allow-Credentials: true' \
--header 'Strict-Transport-Security: max-age=31536000; includeSubDomains' \
--header 'Access-Control-Allow-Methods: *' \
--data 'client_id=MADKALUBAS&client_secret=GshzGRZJjuMUgd2sYHM7&username=test&password=test&grant_type=password'
```

same requests... the only difference if where it is initiated from while still on the same host. super weird.

**Comment by coder89** [comment]
alright, I think I got it 😄 

it's all about the `User-Agent: python` header
if replacing that with whatever else then it works like a charm. 

They must have changed their API to block requests from python scripts 😄

**Comment by mikey0000** [comment]
Yeah they occasionally change their api and break the integration. They could tell me but nah... 😅

**Comment by mikey0000** [comment]
new release out, try 0.3.7

**Comment by coder89** [comment]
Wow, that was ultra quick! Thank you so much! Really appreciate it :)

**Comment by mikey0000** [comment]
In the dev branch I've updated the login to the encrypted login flow so that will be coming too.
